config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :repos do
    post :subscribe, on: :member
    delete :unsubscribe, on: :member
    get :search, on: :collection
    get :email_unsubscribed, on: :member
  end

  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:is_admin) && current_user.is_admin
  end

  constraints resque_web_constraint do
    mount Resque::Server, at: '/resque'  
  end
  root to: "repos#index"
end

app/models/repo.rb
class Repo < ApplicationRecord
  # Schema Repos table
  #   t.string "url"
  #   t.datetime "created_at", null: false
  #   t.datetime "updated_at", null: false
  #   t.string "name"
  #   t.integer "user_id"
  #   t.text "compare"
  #   t.string "description"
  #   t.string "homepage"
  include AASM
  aasm do
    state :created, initial: true
    state :cloned
    state :compared
    state :pulled

    event :do_cloning do 
      transitions from: [:created], to: :cloned
    end  

    event :do_comparing do
      transitions from: [:cloned, :pulled], to: :compared
    end

    event :do_pulling do
      transitions from: [:compared], to: :pulled
    end
  end
  validate :valid_url?
  validates :name, :url, uniqueness: true, presence: true
  belongs_to :user
  has_many :subscribes,  dependent: :destroy
  has_many :locale_keys
  serialize :compare, Hash

  def fetch_description_from_github
    github = Github.new client_id: ENV['CLIENT_ID'], client_secret: ENV['APP_SECRET']
    result = github.repos.get(user_name(url), repo_name(url))
    description = result.description
    homepage = result.homepage
    self.update(description: description, homepage: homepage)
  end

  def user_name(url)
    %r{/([^/]+)/([^/]+)/?\z}o.match(url)[1]
  end

  def repo_name(url)
    %r{/([^/]+)/([^/]+)/?\z}o.match(url)[2].remove('.git')
  end

  def star_github_small
    "https://ghbtns.com/github-btn.html?user=#{user_name(url)}&repo=#{name}&type=star&count=true&size=small"
  end

  def fork_github_small
    "https://ghbtns.com/github-btn.html?user=#{user_name(url)}&repo=#{name}&type=fork&count=true&size=small"
  end

  def read_file_read_me
    if Dir.exist?(cloned_source_path)
      readme = File.read("#{cloned_source_path}/README.md") 
      update(readme: readme)
    end
  end
  
  def locale_path
    "#{cloned_source_path}/config/locales"
  end

  def locale_path_exist?
    update(locale_exist: true) if Dir.exist?(locale_path)
  end
  
  def match_locale?(file)
    supported_locales = ["af", "ar", "az", "be", "bg", "bn", "bs", "ca", "cs", "cy", "da", "de", "de_AT", "de_CH", "de_DE", "el", "el_CY", "en", "en_AU", "en_CA", "en_GB", "en_IE", "en_IN", "en_NZ", "en_US", "en_ZA", "en_CY", "eo", "es", "es_419", "es_AR", "es_CL", "es_CO", "es_CR", "es_EC", "es_ES", "es_MX", "es_NI", "es_PA", "es_PE", "es_US", "es_VE", "et", "eu", "fa", "fi", "fr", "fr_CA", "fr_CH", "fr_FR", "gl", "he", "hi", "hi_IN", "hr", "hu", "id", "is", "it", "it_CH", "ja", "ka", "km", "kn", "ko", "lb", "lo", "lt", "lv", "mk", "ml", "mn", "mr_IN", "ms", "nb", "ne", "nl", "nn", "oc", "or", "pa", "pl", "pt", "pt_BR", "rm", "ro", "ru", "sk", "sl", "sq", "sr", "sw", "ta", "te", "th", "tl", "tr", "tt", "ug", "ur", "uz", "vi", "wo", "zh_CN", "zh_HK", "zh_TW", "zh_YUE"]
    supported_locales.include?(file)
  end

  def locale_keys_of_repo_existing?
    LocaleKey.where(repo_id: self.id).present?
  end

  def change_data_on_localekeys_table
    available_locales = []
    Dir.foreach(locale_path) do |file|
      basename = File.basename(file, '.yml')
      if match_locale?(basename)
        available_locales << file
        locale_files = FlattenYmlFile.perform("#{locale_path}/#{file}")
        locale_files.each do |key, value|
          if locale_keys_of_repo_existing? 
            self.locale_keys.where(locale: basename, key: key).update(value: value)
          else
            LocaleKey.create(locale: basename, key: key, value: value, repo_id: self.id)
          end
        end
      end
    end
    update(multi_language_support: true) if available_locales != ['en.yml']
  end

  def run_compare
    en_keys = LocaleKey.where(repo_id: self.id, locale: 'en').distinct.pluck(:key)
    available_locales = locale_keys.select('locale').where.not(locale: 'en').distinct 
    hash = {}
    available_locales.each do |name| 
      keys = LocaleKey.where(locale: name.locale).distinct.pluck(:key)
      different_keys = en_keys - keys
      hash[name.locale] = different_keys if different_keys != [] 
    end
    update(compare: hash)
    do_comparing!
  end

  def run_clone
    Rugged::Repository.clone_at(self.url, cloned_source_path)
    do_cloning!
  end

  def pull_code
    rugged = Rugged::Repository.new(cloned_source_path)
    rugged.remotes['origin'].fetch
    rugged.checkout(rugged.branches["origin/master"], strategy: :force)
    do_pulling!
  end

  def cloned_source_path
    "tmp/#{name}"
  end

  def self.detect_missing_keys_daily
    Repo.find_each do |repo|
      if !Dir.exists?(repo.locale_path)
        repo.run_clone
      else
        repo.pull_code
      end
      previous_compare = repo.compare
      repo.run_compare
      daily_compare = repo.compare
      repo.send_email_if_missing_keys if previous_compare === daily_compare
    end
  end

  def self.delete_folder_github(path)
    FileUtils.rm_rf(path)
  end

  def valid_url?
    url_regexp = /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix
    errors.add(:url, "Please input correct Url") unless self.url =~ url_regexp 
  end

  def convert_to_git_path
    self.url[-1] == '/' ? self.url.chomp!('/') : self.url
    url = self.url + ".git" 
    name = self.name.gsub(/[-]/, ' ').gsub(/[_]/, ' ').humanize
    update(url: url, name: name)
  end
  
  def self.search(search)
    search ? self.where('name ILIKE ?', "%#{search}%") : self
  end

  def send_email_if_missing_keys
    if compare != {} 
      UserMailer.notify_missing_key_on_locale_for_owner(self.user, self).deliver_now
      if self.subscribes.present?
        subscribes.each do |subscribe|
          user_subscribed = User.find(subscribe.user_id)
          UserMailer.notify_missing_key_on_locale_for_subscribe(user_subscribed, self).deliver_now
        end
      end
    end
  end

  def self.update_repos_table
    Repo.find_each do |repo|
      repo.fetch_description_from_github
      repo.read_file_read_me
      repo.convert_to_git_path
      repo.locale_path_exist?
    end
  end

  def stop_send_email(user)
    Subscribe.where(user_id: user.id, repo_id: self.id).delete_all
  end

  def self.count_search(search)
    self.search(search).count
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  before_action :find_repo, only: %i[edit update show destroy subscribe unsubscribe email_unsubscribed ]
  skip_before_action :authenticate_user!, only: %i[show index]
  def index
    params[:search].present? ? @repos = Repo.search(params[:search]) : @repos = Repo.order(created_at: :DESC)
  end
  
  def new
    @repo = current_user.repos.build
  end
  
  def create
    @repo = current_user.repos.build(repo_params)
    if @repo.save
      Resque.enqueue(RunClone, @repo.id)
      Resque.enqueue(RunUpdateReposTable)
      Resque.enqueue(RunChangeDataOnLocaleKeysTable, @repo.id)
      Resque.enqueue(RunCompare, @repo.id)
      Resque.enqueue(RunSendEmail, @repo.id)
      flash[:success] = "#{@repo.name.capitalize} created successfully"
      redirect_to repos_path
    else
      render :new
    end
  end 

  def edit
  end
  
  def update
    @repo.update_attributes(repo_params)
    if @repo.save
      flash[:success] = "#{@repo.name.capitalize} updated successfully"
      redirect_to repos_path
    else
      render :edit
    end
  end
  
  def show
  end
  
  def destroy
    path = @repo.cloned_source_path
    repo_id = @repo.id
    @repo.destroy
    Resque.enqueue(RunDeleteFolderGithub, path)
    Resque.enqueue(RunDeleteLocaleKeysOfRepo, repo_id)
    flash[:danger] = "#{@repo.name.capitalize} deleted successfully"
    redirect_to repos_path
  end

  def subscribe
    @repo.subscribes.create(user_id: current_user.id)
    flash[:success] = "Subscribed #{@repo.name.capitalize} successfully"
    redirect_to repo_path(@repo)
  end

  def unsubscribe
    @repo.subscribes.where(user_id: current_user.id).destroy_all
    flash[:danger] = "Unsubscribed #{@repo.name.capitalize} successfully"
    redirect_to repo_path(@repo)
  end

  def email_unsubscribed
    @repo.stop_send_email(current_user)
    flash[:danger] = "Unsubscribed #{@repo.name.capitalize} successfully"
    redirect_to repo_path(@repo)
  end

  private
    def find_repo
      @repo = Repo.find(params[:id])
    end
    
    def repo_params
      params.require(:repo).permit(:url, :name, :user_id, :compare, :receive_email)
    end
end

app/helpers/repos_helper.rb
module ReposHelper
  # def indentation(string)
  #   arrays = string.split(".")
  #   result = []
  #   result << arrays[0].split(" ")[1]
  #   arrays.each_with_index { |element, index|
  #     result << element.insert(0, "   "*index) if index > 0
  #   }
  # end

  def subscribed_by_user?(user, repo)
    repo.subscribes.where(user_id: user.id).present? if user.present?
  end
end

app/views/repos/_accordion.html.erb
<div class="accordion" id="accordionExample"> 
  <% @repo.compare.each_with_index do |(locale, missing_keys), index|  %>
    <div class="card">
      <div class="card-header" id="heading<%=index%>">
        <h5 class="mb-0">
          <span class="float-left"><%= locale %><p class="text-secondary font-italic float-right">(<%= missing_keys.count %>)</p></span> 
          <button class="btn btn-link float-right " type="button" data-toggle="collapse" data-target="#collapse-<%=index%>" aria-expanded="true" aria-controls="collapse-<%=index%>">
          <i class="fa fa-caret-down fa-2x"></i>
          </button>
        </h5>
      </div>
      <div id="collapse-<%=index%>" class="collapse " aria-labelledby="heading<%=index%>" data-parent="#accordionExample">
        <div class="card-body">
          <% missing_keys.each do |element|  %>
            <%= element %><br>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="pb-3">
  <span class="text-right text-danger">Total: <%= @repo.compare.keys.count > 0 ?  "#{@repo.compare.keys.count} locales missing key" : "#{@repo.compare.keys.count} locale missing key"%></span>
  <span class="text-danger float-right font-italic">Created at: <%= time_ago_in_words(@repo.created_at) %></span> 
</div>

app/views/repos/_action.html.erb
<% if repo.user == current_user %>
  <%= link_to edit_repo_path(repo) do %>
    <button class="btn badge-primary btn-sm" title="Edit" ><i class="fa fa-edit"></i></button>
  <% end %>
  <% if action_name == 'show'%>
    <%= link_to repo_path(repo), method: :delete, data: { confirm: "Are you sure? "} do %>
      <button class="btn badge-primary btn-sm" title="Destroy"><i class="fa fa-trash"></i></button> 
    <% end %>
  <% end %>
<% end %>
<button class="btn badge-primary btn-sm" title="<%=repo.user.email %>"><%= image_tag repo.user.gravatar_url(size: 20) %></button> 
<button class="btn badge-primary btn-sm " title="link"><a href="<%= repo.url %>" target="_blank" class='link_white'><i class="fa fa-link"></i></a></button>
<button class="btn badge-primary btn-sm " title="Quantity Subscribes"><%=repo.subscribes.count %></button> <br>

app/views/repos/_card_bootstrap.html.erb
<div class="row col-12 mx-0 px-0">
  <% @repos.each do |repo| %>
    <div class="col-4 px-1 pb-2">
      <div class="card-group">
        <div class="card border-primary" style="max-height: 170px;">
            <div class="card-body py-2" >
              <h5 class="card-title text-capitalize text-primary mb-2"><%= link_to repo.name, repo_path(repo) %></h5>
              <p class="card-text text-primary mb-2"><%=repo.description.truncate(40, separator: ' ') if repo.description.present?  %></p>
              <span><%=render 'action', repo: repo %></span>
              <small class="text-muted">Create_at: <%= time_ago_in_words(repo.created_at)%></small>
            </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/repos/_description.html.erb
<%= @repo.description %>
<a href="<%= @repo.homepage %>"><%= @repo.homepage %></a> 

app/views/repos/_form.html.erb
<div class="container-fluid col-lg-6 py-5">
  <%= simple_form_for @repo do |f| %>
    <%= f.input :url, label: false, placeholder: "Enter Url"  %>
    <%= f.input :name, label: false, placeholder: "Enter Name"  %>
    <% if action_name == 'edit' %>
      <%= f.input_field :receive_email, as: :boolean, checked_value: true, unchecked_value: false%>
      <%= f.label :"Unchecked if you do not want to receive missing locale keys email" %>
      <%= f.submit 'Edit', class: 'btn btn-primary btn-block btn-lg' %>
    <% else %>
      <%= f.submit 'Create', class: 'btn btn-primary btn-block btn-lg' %>
    <% end %>
  <% end %>
</div>

app/views/repos/_tab_bootstrap.html.erb
<ul class="nav nav-tabs pt-2" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Compare Locale</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Description</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Read Me</a>
  </li>
</ul>

  <div class="tab-content" id="myTabContent">
    <% if @repo.compared? %>
      <% if @repo.compare != {}%>
        <div class="tab-pane fade show active" id="contact" role="tabpanel" aria-labelledby="contact-tab">
          <%= render 'accordion', repo: @repo %>
        </div>
      <% elsif !@repo.locale_exist %>
        <div class="tab-pane fade show active" id="contact" role="tabpanel" aria-labelledby="contact-tab"><h4 class="text-primary pt-3">We would like to inform that we only support for repo with locale file follow Rails structure</h4></div>
      <% elsif @repo.multi_language_support %>
        <div class="tab-pane fade show active" id="contact" role="tabpanel" aria-labelledby="contact-tab"><h4 class="text-primary pt-3">Oops, <%=@repo.name %> not provide multi-language support</h4></div>
      <% end %>
    <% elsif !@repo.locale_exist%>
      <div class="tab-pane fade show active" id="contact" role="tabpanel" aria-labelledby="contact-tab"><h4 class="text-primary pt-3">We would like to inform that we only support for repo with locale file follow Rails structure</h4></div>
    <% else %>
      <div><h4 class="text-primary pt-3">The process is about to compare. Please take a while ...</h4></div>
    <% end %>
    <div class="tab-pane fade " id="home" role="tabpanel" aria-labelledby="home-tab"><%= render 'description', repo: @repo %></div>
    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab"><%= markdown(@repo.readme) %></div>
  </div>

app/views/repos/_under_header.html.erb
<span>
  <% if subscribed_by_user?(current_user, @repo) %> 
    <%= link_to 'Unsubsbribe', unsubscribe_repo_path(@repo), method: :delete, class: 'btn btn-danger btn-sm' %>
  <% else %>
    <%= link_to 'Subscribe', subscribe_repo_path(@repo), method: :post, class: 'btn btn-success btn-sm' %>
  <% end %> 
<%= render 'action', repo: @repo %>
</span>  

<span class="btn-github float-right">
  <iframe class="gem__ghbtn pt-2" src=<%=@repo.star_github_small%> frameborder="0" scrolling="0" width="100px" height="30px"></iframe>
  <iframe class="gem__ghbtn pt-2" src=<%=@repo.fork_github_small%> frameborder="0" scrolling="0" width="100px" height="30px"></iframe>
</span>

app/views/repos/edit.html.erb
<h3 class="pt-5 text-center text-success mt-3">Edit Repo</h3>
<%= render 'form' %>

app/views/repos/index.html.erb
<div class="container py-5 col-10 px-4">
  <h3 class="text-capitalize text-primary text-center pb-5">Listing of Repos</h3>
  <%= render 'card_bootstrap'%>
  <% count = Repo.count %>
</div>

app/views/repos/new.html.erb
<h3 class="pt-5 text-center text-primary mt-3">Create New Repo</h3>
<%= render 'form' %>

app/views/repos/show.html.erb
<h3 class=" text-center text-primary text-capitalize py-5 "><%= @repo.name %></h3> 
<div class="col-8 offset-2">
  <%= render 'under_header', repo: @repo %>
  <%= render 'tab_bootstrap', repo: @repo %>
</div>