config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :repos do
    post :subscribe, on: :member
    delete :unsubscribe, on: :member
    get :search, on: :collection
    get :email_unsubscribed, on: :member
  end

  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:is_admin) && current_user.is_admin
  end

  constraints resque_web_constraint do
    mount Resque::Server, at: '/resque'  
  end
  root to: "repos#index"
end

app/views/layouts/_messages.html.erb
<div class="container-fluid px-0 text-center ">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> my-0 py-0">
      <a href="#" data-dismiss="alert" class="close">×</a>
        <ul class="my-1 bullet-off">
          <li>
            <%= value %>
          </li>
        </ul>
    </div>
  <% end %>
</div>
  

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <div class="col-6 offset-1">
      <%= form_tag repos_path, class: 'navbar-form navbar-left', method: :get do %>
        <div class="form-inline my-2 my-lg-0 placeholder">
          <%= text_field_tag :search, params[:search], :class =>"form-control", :placeholder=>"Search" %>
        </div>
      <% end %>
    </div>
   
    <div class="col-4">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0 float-right">
        <li class="nav-item ">
            <a href="#"><%=link_to 'Locale Detector', repos_path, class: 'nav-link text-primary'%></a>
          </li>
        <% if user_signed_in? %>
          <li class="nav-item active">
            <a href="#"><%= link_to 'New Repo', new_repo_path, class: "nav-link text-primary" %></a> 
          </li>

          <li class="nav-item ">
            <a href="#"><%=link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-link text-danger'%></a>
          </li>
        <% else %>
          <li class="nav-item">
            <a  href="#"><%= link_to "Sign In", new_user_session_path, class: "nav-link text-primary"%></a>
          </li>

          <li class="nav-item">
            <a href="#"><%=link_to 'Sign Up', new_user_registration_path, class: "nav-link text-primary"%></a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LocaleDetect</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>